tipo:
    resource: "@CartaCartaBundle/Controller/TipoController.php"
    type:     annotation

plato:
    resource: "@CartaCartaBundle/Controller/PlatoController.php"
    type:     annotation

tipoprecio:
    resource: "@CartaCartaBundle/Controller/TipoPrecioController.php"
    type:     annotation

preciototal:
    resource: "@CartaCartaBundle/Controller/PrecioTotalController.php"
    type:     annotation

foto:
    resource: "@CartaCartaBundle/Controller/FotoController.php"
    type:     annotation

comandas:
    resource: "@CartaCartaBundle/Controller/ComandasController.php"
    type:     annotation

cliente:
    resource: "@CartaCartaBundle/Controller/ClienteController.php"
    type:     annotation

index:
    pattern:  /
    defaults: { _controller: CartaCartaBundle:Default:index }