tipo:
    resource: "@CartaCartaBundle/Controller/TipoController.php"
    type:     annotation

plato:
    resource: "@CartaCartaBundle/Controller/PlatoController.php"
    type:     annotation

tipoprecio:
    resource: "@CartaCartaBundle/Controller/TipoPrecioController.php"
    type:     annotation

preciototal:
    resource: "@CartaCartaBundle/Controller/PrecioTotalController.php"
    type:     annotation

foto:
    resource: "@CartaCartaBundle/Controller/FotoController.php"
    type:     annotation

comandas:
    resource: "@CartaCartaBundle/Controller/ComandasController.php"
    type:     annotation

cliente:
    resource: "@CartaCartaBundle/Controller/ClienteController.php"
    type:     annotation
    
principal:
    pattern: /principal
    defaults: { _controller: CartaCartaBundle:Default:index }
    
platos:
  pattern: /platos/{id}
  defaults: { _controller: CartaCartaBundle:Default:platos, id: 1 }

presentacion:
  pattern: /presentacion
  defaults: { _controller: CartaCartaBundle:Default:presentacion }
