parameters:
#    carta_carta.example.class: Carta\CartaBundle\Example

services:
#    carta_carta.example:
#        class: %carta_carta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
