// // CREATE TABLE Comandas (id INT AUTO_INCREMENT NOT NULL, idplatos INT DEFAULT NULL, num_factura INT NOT NULL, id_platos INT NOT NULL, cantidad INT NOT NULL, fecha DATETIME NOT NULL, mesa INT NOT NULL, INDEX IDX_8E3BFDBE79949C86 (idplatos), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Platos (id INT AUTO_INCREMENT NOT NULL, tipo VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, precio DOUBLE PRECISION NOT NULL, foto_id VARCHAR(255) NOT NULL, INDEX IDX_1A85341C702D1D47 (tipo), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Tipos (id INT AUTO_INCREMENT NOT NULL, tipo VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE Comandas ADD CONSTRAINT FK_8E3BFDBE79949C86 FOREIGN KEY (idplatos) REFERENCES Platos (id);
ALTER TABLE Platos ADD CONSTRAINT FK_1A85341C702D1D47 FOREIGN KEY (tipo) REFERENCES Tipos (tipo);
