parameters:
#    mdw_carta.example.class: MDW\CartaBundle\Example

services:
#    mdw_carta.example:
#        class: %mdw_carta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
