<?php

namespace MDW\CartaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatosRepository extends EntityRepository
{
}
