<?php

namespace Carta\CartaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioTotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioTotalRepository extends EntityRepository
{
}
