carta_carta:
    resource: "@CartaCartaBundle/Resources/config/routing.yml"
    prefix:   /


# mdw_carta:
#     resource: "@MDWCartaBundle/Resources/config/routing.yml"
#     prefix:   /

# mdw_demo:
#     resource: "@MDWDemoBundle/Resources/config/routing.yml"
#     prefix:   /